In [1]:
import os
from shutil import copyfile
from xia2pipe.connector import SQL
import numpy as np
from tqdm import tqdm

import pandas

In [10]:
def compute_volume(df):
    # only for monoclinic...
    df['volume'] = df['a'] * df['b'] * df['c'] * np.sin(np.radians(df['beta'])) / 1000. # nm^3
    return

In [2]:
password = os.environ["SARSPASS"]

db = SQL({
          "host":               "cfeld-vm05.desy.de",
          "database":           "SARS_COV_2_Analysis_v2",
          "user":               "reader",
          "password":           password,
          "connection_timeout": 60,
          "auth_plugin":        "mysql_native_password",
          'autocommit':         True, 
})

upsteam_db = SQL({
          "host":               "cfeld-vm05.desy.de",
          "database":           "SARS_COV_2_v2",
          "user":               "reader",
          "password":           password,
          "connection_timeout": 60,
          "auth_plugin":        "mysql_native_password",
          'autocommit':         True, 
})

In [3]:
TARGET = 'MPro'
METHOD = 'dmpl2-aligned'
#METHOD = 'dmpl2-qfit'

MIN_RES   = 2.2
MIN_RFREE = 0.25

FILTER_OUT_HITS = True

In [4]:
qry = db.select(['refinement_id, data_reduction_id, final_pdb_path, refinement_mtz_path, rfree, rwork, resolution_cut'],
                'Refinement',
                {'method' : METHOD})

In [9]:
# update with info from Data_Reduction table
for q in tqdm(qry):
    
    red = db.select(['crystal_id, run_id, a, b, c, alpha, beta, gamma, method, mtz_path'], 
                    'Data_Reduction', 
                    {'data_reduction_id' : q['data_reduction_id']})
    q.update(red[0])
    
    red = upsteam_db.select(['beamline'], 
                             'Diffractions', 
                            {'crystal_id' : q['crystal_id']})
    q.update(red[0])
    
    red = upsteam_db.select(['target_id, compound_drop_id', 'crystal_id', 'creator_id'], 
                             'Crystals', 
                            {'crystal_id' : q['crystal_id']})
    q.update(red[0])
    
    red = upsteam_db.select(['compound_id'], 
                             'Compound_Drops', 
                            {'compound_drop_id' : q['compound_drop_id']})
    q.update(red[0])
    
    red = upsteam_db.select(['name'], 
                         'Compounds', 
                        {'compound_id' : q['compound_id']})
    q.update(red[0])

100%|██████████| 14355/14355 [01:15<00:00, 190.91it/s]

In [11]:
# make sure we have a unique set of crystal_id/run_id
# by choosing the best rfree refinement result for each xtal

filtered_qry = {}

for q in qry:
    
    if q['target_id'].lower() == TARGET.lower():
    
        k = (q['crystal_id'], q['run_id'])

        if k in filtered_qry.keys():
            if q['rfree'] < filtered_qry[k]['rfree']:
                filtered_qry[k] = q
        else:
            filtered_qry[k] = q

print(len(qry), len(filtered_qry))

14355 5150

In [19]:
prior_to_quality_selection = pandas.DataFrame(filtered_qry.values())
compute_volume(prior_to_quality_selection)

In [23]:
prior_to_quality_selection.to_csv("./unique_mpro_datasets_prior_to_downselection.csv", index=False)

In [24]:
with open('hits.txt', 'r') as f:
    hits = f.read().split('\n')

def is_hit(qry):
    return qry['compound_id'] in hits

In [25]:
# format as string for transfer to other python env

panda_res = []

for q in filtered_qry.values():
    if q['rfree'] and q['resolution_cut']:
        
        if (q['rfree'] < MIN_RFREE) and \
           (q['resolution_cut'] < MIN_RES) and \
           q['final_pdb_path'].endswith('_003_aligned.pdb') and \
           (not FILTER_OUT_HITS or not is_hit(q)):
            panda_res.append(q)   
            
print(len(panda_res))

1147

In [26]:
df = pandas.DataFrame(panda_res)
compute_volume(df)

df['dataset_name'] = df['final_pdb_path'].apply(os.path.basename)
df['dataset_name'] = df['dataset_name'].apply(lambda x : x[:-4])

df = df[[
    'dataset_name',
    'refinement_id', 
    'data_reduction_id',
    'crystal_id',
    'run_id',
    'beamline',
    'creator_id',
    'final_pdb_path',
    'mtz_path',
    'refinement_mtz_path',
    'compound_drop_id', 'compound_id', 'name', 
    'method',
    'rfree',
    'rwork',
    'resolution_cut',
    'a',
    'b',
    'c',
    'alpha',
    'beta',
    'gamma',        
    'volume'
]]

df

,dataset_name,refinement_id,data_reduction_id,crystal_id,run_id,beamline,creator_id,final_pdb_path,mtz_path,refinement_mtz_path,...,rfree,rwork,resolution_cut,a,b,c,alpha,beta,gamma,volume
0,l7p01_16_001_003_aligned,57379,9772,MPro_1000_0,1,p11,Susanne/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2281,0.1921,1.750196,113.705011,53.312778,44.646043,90.0,103.075237,90.0,263.624500
1,l6p23_05_001_003_aligned,57383,9776,MPro_1005_0,1,p11,Ilona/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2179,0.1895,1.469575,113.385946,53.345109,44.662966,90.0,103.007571,90.0,263.215873
2,l6p23_10_001_003_aligned,57385,9780,MPro_1010_0,1,p11,Ilona/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2108,0.1817,1.420112,113.030331,53.120003,44.642397,90.0,102.981136,90.0,261.190584
3,l6p23_13_001_003_aligned,57387,9782,MPro_1013_0,1,p11,Ilona/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2020,0.1800,1.379733,112.828683,53.031398,44.730019,90.0,102.876152,90.0,260.910329
4,l6p22_16_001_003_aligned,65288,21479,MPro_1024_1,1,p11,Najeeb/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/proc...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2457,0.2069,1.750000,113.270000,53.270000,44.490000,90.0,102.956000,90.0,261.613890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,l2p17_01_001_003_aligned,65495,20301,MPro_132_0,1,p11,Susanne/Robin,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/proc...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2360,0.2059,1.520000,112.970000,53.040000,44.590000,90.0,102.904000,90.0,260.432634
1143,l2p22_16_001_003_aligned,65764,20384,MPro_167_1,1,p11,Najeeb/Robin,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/proc...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2443,0.2120,1.800000,113.740000,53.540000,44.560000,90.0,103.018000,90.0,264.380357
1144,l11p20_15_002_003_aligned,66037,19803,MPro_2103_0,2,None,Ilona/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/proc...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2373,0.2132,1.610000,112.760000,53.100000,44.630000,90.0,102.715000,90.0,260.671463
1145,l11p22_10_001_003_aligned,66134,19826,MPro_2232_0,1,p11,Nadine/Christina,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/proc...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2445,0.2224,1.740000,113.700000,53.570000,44.630000,90.0,102.777000,90.0,265.106092
1146,l2p06_13_003_003_aligned,67516,20178,MPro_54_0,3,None,Susanne/Arwen,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,/asap3/petra3/gpfs/p11/2020/data/11009999/proc...,/asap3/petra3/gpfs/p11/2020/data/11009999/scra...,...,0.2380,0.2111,1.450000,112.350000,52.740000,44.760000,90.0,102.868000,90.0,258.557412

In [27]:
csv_file = 'pdbs_{}_{}.csv'.format(TARGET, METHOD)
print('-->', csv_file)
df.to_csv(csv_file, index=False)

--> pdbs_MPro_dmpl2-aligned.csv

In [28]:
pandas.set_option('display.max_colwidth', 1000)
pandas.set_option('display.max_rows', 5)
df

,dataset_name,refinement_id,data_reduction_id,crystal_id,run_id,beamline,creator_id,final_pdb_path,mtz_path,refinement_mtz_path,...,rfree,rwork,resolution_cut,a,b,c,alpha,beta,gamma,volume
0,l7p01_16_001_003_aligned,57379,9772,MPro_1000_0,1,p11,Susanne/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/l7p01_16/l7p01_16_001/l7p01_16_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/l7p01_16/l7p01_16_001/DataFiles/SARSCOV2_l7p01_16_001_free.mtz,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/l7p01_16/l7p01_16_001/l7p01_16_001_003_aligned.mtz,...,0.2281,0.1921,1.750196,113.705011,53.312778,44.646043,90.0,103.075237,90.0,263.624500
1,l6p23_05_001_003_aligned,57383,9776,MPro_1005_0,1,p11,Ilona/Huijong,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/l6p23_05/l6p23_05_001/l6p23_05_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/l6p23_05/l6p23_05_001/DataFiles/SARSCOV2_l6p23_05_001_free.mtz,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/l6p23_05/l6p23_05_001/l6p23_05_001_003_aligned.mtz,...,0.2179,0.1895,1.469575,113.385946,53.345109,44.662966,90.0,103.007571,90.0,263.215873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,l11p22_10_001_003_aligned,66134,19826,MPro_2232_0,1,p11,Nadine/Christina,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/XDSv1_noice_dmpl2/l11p22_10/l11p22_10_001/l11p22_10_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/processed/reindex1_noice/l11p22_10/l11p22_10_001/full/l11p22_10_001_F.mtz,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/XDSv1_noice_dmpl2/l11p22_10/l11p22_10_001/l11p22_10_001_003_aligned.mtz,...,0.2445,0.2224,1.740000,113.700000,53.570000,44.630000,90.0,102.777000,90.0,265.106092
1146,l2p06_13_003_003_aligned,67516,20178,MPro_54_0,3,None,Susanne/Arwen,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/XDSv1_noice_dmpl2/l2p06_13/l2p06_13_003/l2p06_13_003_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/processed/reindex1_noice/l2p06_13/l2p00_16_003/full/l2p00_16_003_F.mtz,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/XDSv1_noice_dmpl2/l2p06_13/l2p06_13_003/l2p06_13_003_003_aligned.mtz,...,0.2380,0.2111,1.450000,112.350000,52.740000,44.760000,90.0,102.868000,90.0,258.557412

In [29]:
# fetch the pdbs & mtzs for tarballing and archiving

os.mkdir('./selected_dataset_archive_2024-08-07')
os.mkdir('./selected_dataset_archive_2024-08-07/pdb')
os.mkdir('./selected_dataset_archive_2024-08-07/map')
os.mkdir('./selected_dataset_archive_2024-08-07/mtz')
df.to_csv('./selected_dataset_archive_2024-08-07/metadata.csv', index=False)

for ir,r in tqdm(df.iterrows()):
    try:
        
        if r['mtz_path'].startswith('/asap3/petra3/gpfs/p11/2020/data/11010091'):
            mtz_path = r['mtz_path'].replace('11010091', '11009999')
        else:
            mtz_path = r['mtz_path']
        
        dataset_name = os.path.basename(r['final_pdb_path'])[:-4]
        
        copyfile(r['final_pdb_path'],      os.path.join('./selected_dataset_archive_2024-08-07/pdb', dataset_name + '.pdb'))
        copyfile(mtz_path,                 os.path.join('./selected_dataset_archive_2024-08-07/mtz', dataset_name + '_data.mtz'))
        copyfile(r['refinement_mtz_path'], os.path.join('./selected_dataset_archive_2024-08-07/map', dataset_name + '_map.mtz'))
    except Exception as e:
        print(e)

FileExistsError: [Errno 17] File exists: './selected_dataset_archive_2024-08-07'

## extract the hits, look for one that has a lot of datasets

In [30]:
# format as string for transfer to other python env
pandas.set_option('display.max_rows', 300)

panda_res_hits = []

for q in filtered_qry.values():
#    if q['rfree'] and q['resolution_cc']:
        
#         if (q['rfree'] < MIN_RFREE) and \
#            (q['resolution_cc'] < MIN_RES) and \
#            q['final_pdb_path'].endswith('_003_aligned.pdb') and \
        if is_hit(q):
            panda_res_hits.append(q)   
            
print(len(panda_res_hits))

df_hits = pandas.DataFrame(panda_res_hits)
df_hits = df_hits.sort_values('compound_id', axis=0)
df_hits

256

,refinement_id,data_reduction_id,final_pdb_path,refinement_mtz_path,rfree,rwork,resolution_cut,crystal_id,run_id,a,...,beta,gamma,method,mtz_path,target_id,compound_drop_id,creator_id,compound_id,name,beamline
73,60119,23250,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5309_0/MPro_5309_0_001/MPro_5309_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5309_0/MPro_5309_0_001/MPro_5309_0_001_003_aligned.mtz,0.2063,0.1768,1.440046,MPro_5309_0,1,113.387630,...,103.065797,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5309_0/MPro_5309_0_001/DataFiles/SARSCOV2_MPro_5309_0_001_free.mtz,MPro,5309,Susanne/Robin,DOM_SIM_015,None,p11
47,63243,35941,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_3926_0/MPro_3926_0_001/MPro_3926_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_3926_0/MPro_3926_0_001/MPro_3926_0_001_001_aligned.mtz,0.2645,0.2341,2.233000,MPro_3926_0,1,114.070000,...,101.606000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/autoproc1/MPro_3926_0/MPro_3926_0_001/staraniso_alldata-unique.mtz,MPro,3926,Susanne/Huijong,DOM_SIM_015,None,p11
51,63373,36121,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4110_1/MPro_4110_1_001/MPro_4110_1_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4110_1/MPro_4110_1_001/MPro_4110_1_001_001_aligned.mtz,0.2726,0.2294,2.379000,MPro_4110_1,1,113.326000,...,101.025000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/autoproc1/MPro_4110_1/MPro_4110_1_001/staraniso_alldata-unique.mtz,MPro,4110,Nadine/arwen,DOM_SIM_072,None,p11
50,59496,12447,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4110_0/MPro_4110_0_001/MPro_4110_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4110_0/MPro_4110_0_001/MPro_4110_0_001_003_aligned.mtz,0.2685,0.2263,2.128620,MPro_4110_0,1,113.899263,...,101.071360,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_4110_0/MPro_4110_0_001/DataFiles/SARSCOV2_MPro_4110_0_001_free.mtz,MPro,4110,Nadine/arwen,DOM_SIM_072,None,p11
86,56333,24232,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A_dmpl2/MPro_5605_0/MPro_5605_0_001/MPro_5605_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A_dmpl2/MPro_5605_0/MPro_5605_0_001/MPro_5605_0_001_003_aligned.mtz,0.2543,0.2141,1.700057,MPro_5605_0,1,112.483125,...,102.811039,90.0,DIALS_1p7A-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A/MPro_5605_0/MPro_5605_0_001/DataFiles/SARSCOV2_MPro_5605_0_001_free.mtz,MPro,5605,Susanne/Robin,DOM_SIM_072,None,p11
52,63377,36125,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4114_1/MPro_4114_1_001/MPro_4114_1_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4114_1/MPro_4114_1_001/MPro_4114_1_001_001_aligned.mtz,0.2376,0.2154,2.318000,MPro_4114_1,1,113.875000,...,102.125000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/autoproc1/MPro_4114_1/MPro_4114_1_001/staraniso_alldata-unique.mtz,MPro,4114,Nadine/arwen,DOM_SIM_074,None,p11
87,60311,23777,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5610_0/MPro_5610_0_001/MPro_5610_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5610_0/MPro_5610_0_001/MPro_5610_0_001_003_aligned.mtz,0.2111,0.1844,1.758636,MPro_5610_0,1,114.314854,...,103.001552,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5610_0/MPro_5610_0_001/DataFiles/SARSCOV2_MPro_5610_0_001_free.mtz,MPro,5610,Susanne/Robin,DOM_SIM_074,None,p11
88,60312,23779,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5610_2/MPro_5610_2_001/MPro_5610_2_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5610_2/MPro_5610_2_001/MPro_5610_2_001_001_aligned.mtz,0.2268,0.2051,2.010912,MPro_5610_2,1,112.649349,...,102.932121,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5610_2/MPro_5610_2_001/DataFiles/SARSCOV2_MPro_5610_2_001_free.mtz,MPro,5610,Nadine/Diogo,DOM_SIM_074,None,p11
116,63376,36124,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4114_0/MPro_4114_0_001/MPro_4114_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4114_0/MPro_4114_0_001/MPro_4114_0_001_001_aligned.mtz,0.2429,0.2103,2.222000,MPro_4114_0,1,113.925000,...,101.917000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/autoproc1/MPro_4114_0/MPro_4114_0_001/staraniso_alldata-unique.mtz,MPro,4114,Nadine/arwen,DOM_SIM_074,None,p11
89,56353,24245,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A_dmpl2/MPro_5663_0/MPro_5663_0_001/MPro_5663_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A_dmpl2/MPro_5663_0/MPro_5663_0_001/MPro_5663_0_001_003_aligned.mtz,0.2647,0.2235,1.699994,MPro_5663_0,1,113.780997,...,103.060117,90.0,DIALS_1p7A-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A/MPro_5663_0/MPro_5663_0_001/DataFiles/SARSCOV2_MPro_5663_0_001_free.mtz,MPro,5663,Nadine/Robin,DOM_SIM_123,None,p11
90,60324,23790,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5663_1/MPro_5663_1_001/MPro_5663_1_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5663_1/MPro_5663_1_001/MPro_5663_1_001_003_aligned.mtz,0.2041,0.1855,1.450180,MPro_5663_1,1,113.409964,...,103.059501,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5663_1/MPro_5663_1_001/DataFiles/SARSCOV2_MPro_5663_1_001_free.mtz,MPro,5663,Nadine/Robin,DOM_SIM_123,None,p11
91,60325,23791,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5663_2/MPro_5663_2_001/MPro_5663_2_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5663_2/MPro_5663_2_001/MPro_5663_2_001_003_aligned.mtz,0.2141,0.1764,1.830401,MPro_5663_2,1,112.625459,...,102.920874,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5663_2/MPro_5663_2_001/DataFiles/SARSCOV2_MPro_5663_2_001_free.mtz,MPro,5663,Nadine/Robin,DOM_SIM_123,None,p11
228,63301,36024,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4010_0/MPro_4010_0_001/MPro_4010_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4010_0/MPro_4010_0_001/MPro_4010_0_001_001_aligned.mtz,0.2424,0.2093,2.189000,MPro_4010_0,1,113.115000,...,102.533000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/autoproc1/MPro_4010_0/MPro_4010_0_001/staraniso_alldata-unique.mtz,MPro,4010,Sebastian/Huijong,DOM_SIM_130,None,p11
93,60355,23448,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5711_0/MPro_5711_0_001/MPro_5711_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5711_0/MPro_5711_0_001/MPro_5711_0_001_003_aligned.mtz,0.1976,0.1832,1.549719,MPro_5711_0,1,112.960785,...,102.831137,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5711_0/MPro_5711_0_001/DataFiles/SARSCOV2_MPro_5711_0_001_free.mtz,MPro,5711,Xavier//Huijong,DOM_SIM_130,None,p11
92,67549,38263,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/XDSv1_noice_dmpl2/MPro_5703_1/MPro_5703_1_001/MPro_5703_1_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/XDSv1_noice_dmpl2/MPro_5703_1/MPro_5703_1_001/MPro_5703_1_001_003_aligned.mtz,0.2414,0.2116,1.640000,MPro_5703_1,1,112.370000,...,102.673000,90.0,xds_reindex1_noice,/asap3/petra3/gpfs/p11/2020/data/11009999/processed/reindex1_18-22_noice/MPro_5703_1/MPro_5703_1_001/full/MPro_5703_1_001_F.mtz,MPro,5703,Xavier/Huijong,DOM_SIM_132,None,p11
48,63303,36026,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4012_0/MPro_4012_0_001/MPro_4012_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4012_0/MPro_4012_0_001/MPro_4012_0_001_001_aligned.mtz,0.2538,0.2163,2.319000,MPro_4012_0,1,113.756000,...,101.898000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/autoproc1/MPro_4012_0/MPro_4012_0_001/staraniso_alldata-unique.mtz,MPro,4012,Sebastian/Huijong,DOM_SIM_132,None,p11
49,59490,12439,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4104_0/MPro_4104_0_001/MPro_4104_0_001_002_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4104_0/MPro_4104_0_001/MPro_4104_0_001_002_aligned.mtz,0.2476,0.2310,1.979431,MPro_4104_0,1,113.416251,...,101.289928,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_4104_0/MPro_4104_0_001/DataFiles/SARSCOV2_MPro_4104_0_001_free.mtz,MPro,4104,Hina/arwen,DOM_SIM_161,None,p11
235,64147,36999,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5377_0/MPro_5377_0_001/MPro_5377_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5377_0/MPro_5377_0_001/MPro_5377_0_001_001_aligned.mtz,0.2532,0.2271,1.582000,MPro_5377_0,1,112.765000,...,102.909000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11010091/scratch_cc/autoproc1/MPro_5377_0/MPro_5377_0_001/staraniso_alldata-unique.mtz,MPro,5377,Hina/Robin,DOM_SIM_161,None,p11
95,60439,23848,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5885_2/MPro_5885_2_001/MPro_5885_2_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5885_2/MPro_5885_2_001/MPro_5885_2_001_003_aligned.mtz,0.2155,0.1821,1.618369,MPro_5885_2,1,113.852648,...,102.906755,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5885_2/MPro_5885_2_001/DataFiles/SARSCOV2_MPro_5885_2_001_free.mtz,MPro,5885,Nadine/Robin,DOM_SIM_234,None,p11
96,60440,23849,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5885_3/MPro_5885_3_001/MPro_5885_3_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5885_3/MPro_5885_3_001/MPro_5885_3_001_001_aligned.mtz,0.2460,0.2244,2.230109,MPro_5885_3,1,112.987531,...,102.731620,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5885_3/MPro_5885_3_001/DataFiles/SARSCOV2_MPro_5885_3_001_free.mtz,MPro,5885,Nadine/Robin,DOM_SIM_234,None,p11
229,63671,32683,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4637_0/MPro_4637_0_002/MPro_4637_0_002_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4637_0/MPro_4637_0_002/MPro_4637_0_002_001_aligned.mtz,0.2452,0.2460,1.997000,MPro_4637_0,2,111.868000,...,102.309000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200421/MPro_4637_0_2/MPro_4637_0_2_ap_0_run2_anom_staraniso_alldata-unique.mtz,MPro,4637,Susanne/Huijong,DOM_SIM_400,None,p14
97,60462,23871,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5912_0/MPro_5912_0_001/MPro_5912_0_001_002_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5912_0/MPro_5912_0_001/MPro_5912_0_001_002_aligned.mtz,0.2136,0.1879,1.720630,MPro_5912_0,1,112.327737,...,102.747481,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5912_0/MPro_5912_0_001/DataFiles/SARSCOV2_MPro_5912_0_001_free.mtz,MPro,5912,Hina/Robin,DOM_SIM_400,None,p11
99,60464,23873,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5912_2/MPro_5912_2_001/MPro_5912_2_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5912_2/MPro_5912_2_001/MPro_5912_2_001_003_aligned.mtz,0.1970,0.1783,1.499923,MPro_5912_2,1,112.383912,...,102.674969,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5912_2/MPro_5912_2_001/DataFiles/SARSCOV2_MPro_5912_2_001_free.mtz,MPro,5912,Hina/Robin,DOM_SIM_400,None,p11
98,60463,23872,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5912_1/MPro_5912_1_001/MPro_5912_1_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5912_1/MPro_5912_1_001/MPro_5912_1_001_003_aligned.mtz,0.2208,0.1928,1.708402,MPro_5912_1,1,113.005514,...,102.890885,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5912_1/MPro_5912_1_001/DataFiles/SARSCOV2_MPro_5912_1_001_free.mtz,MPro,5912,Hina/Robin,DOM_SIM_400,None,p11
231,64023,32811,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5159_0/MPro_5159_0_001/MPro_5159_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5159_0/MPro_5159_0_001/MPro_5159_0_001_001_aligned.mtz,0.2432,0.2161,2.628000,MPro_5159_0,1,112.687000,...,101.793000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200422/MPro_5159_0_1/MPro_5159_0_1_ap_0_run1_anom_staraniso_alldata-unique.mtz,MPro,5159,Hina/Robin,DOM_SIM_449,None,p13
103,60542,23956,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_6128_1/MPro_6128_1_001/MPro_6128_1_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_6128_1/MPro_6128_1_001/MPro_6128_1_001_003_aligned.mtz,0.2240,0.1913,1.569486,MPro_6128_1,1,112.753046,...,102.897822,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_6128_1/MPro_6128_1_001/DataFiles/SARSCOV2_MPro_6128_1_001_free.mtz,MPro,6128,Hina/Robin,DOM_SIM_449,None,p11
102,56594,24403,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A_dmpl2/MPro_6128_0/MPro_6128_0_001/MPro_6128_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A_dmpl2/MPro_6128_0/MPro_6128_0_001/MPro_6128_0_001_003_aligned.mtz,0.2692,0.2296,1.699833,MPro_6128_0,1,113.457760,...,103.075811,90.0,DIALS_1p7A-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_1p7A/MPro_6128_0/MPro_6128_0_001/DataFiles/SARSCOV2_MPro_6128_0_001_free.mtz,MPro,6128,Hina/Robin,DOM_SIM_449,None,p11
232,64024,32812,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5159_1/MPro_5159_1_002/MPro_5159_1_002_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5159_1/MPro_5159_1_002/MPro_5159_1_002_001_aligned.mtz,0.2311,0.2465,1.917000,MPro_5159_1,2,113.128000,...,102.158000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200422/MPro_5159_1_2/MPro_5159_1_2_ap_1_run2_anom_staraniso_alldata-unique.mtz,MPro,5159,Hina/Robin,DOM_SIM_449,None,p13
54,59854,12882,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4763_0/MPro_4763_0_001/MPro_4763_0_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4763_0/MPro_4763_0_001/MPro_4763_0_001_003_aligned.mtz,0.2095,0.1860,1.539936,MPro_4763_0,1,113.396255,...,102.941369,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_4763_0/MPro_4763_0_001/DataFiles/SARSCOV2_MPro_4763_0_001_free.mtz,MPro,4763,Nadine/Huijong,DOM_SIM_486,None,p11
55,59855,12883,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4763_1/MPro_4763_1_001/MPro_4763_1_001_003_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_4763_1/MPro_4763_1_001/MPro_4763_1_001_003_aligned.mtz,0.2185,0.1872,1.830083,MPro_4763_1,1,113.322490,...,102.891156,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_4763_1/MPro_4763_1_001/DataFiles/SARSCOV2_MPro_4763_1_001_free.mtz,MPro,4763,Nadine/Huijong,DOM_SIM_486,None,p11
237,64516,32955,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5957_1/MPro_5957_1_002/MPro_5957_1_002_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5957_1/MPro_5957_1_002/MPro_5957_1_002_001_aligned.mtz,0.2335,0.1991,2.157000,MPro_5957_1,2,112.014000,...,102.629000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200428/MPro_5957_1_2/MPro_5957_1_2_ap_1_run2_anom_staraniso_alldata-unique.mtz,MPro,5957,Susanne/Robin,DOM_SIM_538,None,p14
230,63678,32694,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4649_0/MPro_4649_0_002/MPro_4649_0_002_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_4649_0/MPro_4649_0_002/MPro_4649_0_002_001_aligned.mtz,0.2456,0.2515,2.238000,MPro_4649_0,2,113.744000,...,101.732000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200421/MPro_4649_0_2/MPro_4649_0_2_ap_0_run2_anom_staraniso_alldata-unique.mtz,MPro,4649,Hina/Huijong,DOM_SIM_538,None,p14
238,64517,32956,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5957_2/MPro_5957_2_002/MPro_5957_2_002_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5957_2/MPro_5957_2_002/MPro_5957_2_002_001_aligned.mtz,0.2318,0.2040,1.956000,MPro_5957_2,2,112.486000,...,102.796000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200428/MPro_5957_2_2/MPro_5957_2_2_ap_2_run2_anom_staraniso_alldata-unique.mtz,MPro,5957,Susanne/Robin,DOM_SIM_538,None,p14
236,64515,32954,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5957_0/MPro_5957_0_010/MPro_5957_0_010_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5957_0/MPro_5957_0_010/MPro_5957_0_010_001_aligned.mtz,0.2183,0.2066,1.568000,MPro_5957_0,10,113.562000,...,102.932000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/EMBL/download/20200428/MPro_5957_0_10/MPro_5957_0_10_ap_0_run10_anom_staraniso_alldata-unique.mtz,MPro,5957,Susanne/Robin,DOM_SIM_538,None,p14
58,64050,36876,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5254_1/MPro_5254_1_002/MPro_5254_1_002_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5254_1/MPro_5254_1_002/MPro_5254_1_002_001_aligned.mtz,0.2372,0.2304,1.963000,MPro_5254_1,2,113.901000,...,101.603000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11010091/scratch_cc/autoproc1/MPro_5254_1/MPro_5254_1_002/staraniso_alldata-unique.mtz,MPro,5254,Sebastian/Sebastian,SPE_A06935312,FUSIDIC ACID,p11
56,64049,36874,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5254_0/MPro_5254_0_001/MPro_5254_0_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/staraniso_dmpl2/MPro_5254_0/MPro_5254_0_001/MPro_5254_0_001_001_aligned.mtz,0.2449,0.2411,1.941000,MPro_5254_0,1,113.779000,...,102.069000,90.0,staraniso,/asap3/petra3/gpfs/p11/2020/data/11010091/scratch_cc/autoproc1/MPro_5254_0/MPro_5254_0_001/staraniso_alldata-unique.mtz,MPro,5254,Sebastian/Sebastian,SPE_A06935312,FUSIDIC ACID,p11
57,60068,23760,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5254_1/MPro_5254_1_001/MPro_5254_1_001_001_aligned.pdb,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS_dmpl2/MPro_5254_1/MPro_5254_1_001/MPro_5254_1_001_001_aligned.mtz,0.2439,0.2323,2.030124,MPro_5254_1,1,114.109214,...,101.405149,90.0,DIALS-dials,/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc/DIALS/MPro_5254_1/MPro_5254_1_001/DataFiles/SARSCOV2_MPro_5254_1_001_free.mtz,MPro,5254,Sebastian/Sebastian,SPE_A06935312,FUSIDIC ACID,p11

In [31]:
selected_hit = 'TGI'

o_dir = 'hit_datasets/' + selected_hit
if not os.path.exists(o_dir):
    os.mkdir(o_dir)

#sel_df = df_hits[ df_hits['name'] == selected_hit ]
sel_df = df_hits[ df_hits['compound_id'] == 'SPE_A39935389' ]

for idx, l in sel_df.iterrows():
    copyfile(l['refinement_mtz_path'], o_dir+'/m%04d.mtz' % idx)
    copyfile(l['final_pdb_path'],      o_dir+'/m%04d.pdb' % idx)